<?php
// use (vendor) library as functions(?)
use Psr\Http\Message\ResponseInterface as Response;
use Psr\Http\Message\ServerRequestInterface as Request;
use Slim\Factory\AppFactory;
// to install, use command: composer require middlewares/trailing-slash
use Middlewares\TrailingSlash;

// Composer will load whatever is needed by this path (it's in current project>vender>autoload.php)
// vender folder is generated by $composer install. first run this command before editing the project
require __DIR__ . '/vendor/autoload.php';
// link database connection
require __DIR__ . '/src/config/db.php';

// slim configuration line 12 to 21
$app = AppFactory::create();

if (empty(getenv('IDP_ENVIRONMENT'))) {
    // ! important: set the path from the Document Root Directory
    $app->setBasePath('/Kang_Yan_Portfolio/api');
}


// Middleware https://www.slimframework.com/docs/v4/concepts/middleware.html
$app->addRoutingMiddleware();
    // add middleware to let users get the right URL with or without "/" in the end 
    // and add the "/" in routers>php files
$app->add(new TrailingSlash(true));

$errorMiddleware = $app->addErrorMiddleware(true, true, true);

// load routers
require __DIR__ . '/src/routers/projects.php';

$app->get('/', function (Request $request, Response $response, $args) {
    $response->getBody()->write("This is the projects API!");
    return $response
        ->withHeader('Content-Type', 'application/json');
});

$app->run();
